name: Deploy v2

on:
  push:
    branches: [ v2 ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.mibvc.com.ar
          username: ftp_bvconline_576
          password: ${{ secrets.ftp_password }}
          server-dir: public_html/v2/
